confluent_package_filename = "kafka_2.13-3.2.0.tgz"
ip_to_connect_from = "127.0.0.1/32"
ssh_key_name = "msk"
role_in_service_provider_account = "arn:aws:iam::ACCOUNTID:role/somerole"
state_bucket = "test-bucket"